command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

# CapsLock
[keyindicator]
instance=CAPS
interval=once
signal=11

# NumLock
[keyindicator]
instance=NUM
interval=once
signal=11

# CPU temp
[temperature]
label=TEMP
interval=2

# CPU usage
[cpu_usage]
label=CPU
interval=1
min_width=CPU: 100.00%
separator=true

# Disk usage
[disk]
label=
interval=30
separator=true

# IP address
[iface]
color=#FFFFFF
interval=10
separator=true

# PLayerctl
[mediaplayer]
instance=spotify
interval=5
signal=10

# Volume indicator
[volume]
label=
instance=Master
interval=1

# Date Time
[time]
command=date '+%H:%M:%S     %d/%m/%Y'
interval=1
